import fs from "fs";
import path from "path";
import {fileURLToPath} from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// 读取模板文件和数据文件
const templatePath = path.join(
    __dirname,
    "src",
    "test",
    "testData",
    "framework",
    "dejavu",
    "template",
    "code-generator.dejavu",
);
const dataPath = path.join(
    __dirname,
    "src",
    "test",
    "testData",
    "framework",
    "dejavu",
    "template",
    "code-generator.data.json",
);

const templateContent = fs.readFileSync(templatePath, "utf8");
const dataContent = fs.readFileSync(dataPath, "utf8");
const data = JSON.parse(dataContent);

console.log("=== 模板内容 ===");
console.log(templateContent);
console.log("\n=== 数据内容 ===");
console.log(JSON.stringify(data, null, 2));
console.log("\n=== 期望渲染结果 ===");
console.log(
    "# Code Generator Test,\n\n- Java: 11\n- Kotlin: 1.7\n- IntelliJ: 2025.3\n\nGenerated by Dejavu template engine.",
);
