package dejavu.engine

import com.intellij.openapi.project.ProjectManager
import org.junit.Test
import org.junit.Assert.assertEquals

class DejavuEngineTest {
    @Test
    fun testRender() {
        // 获取当前项目
        val project = ProjectManager.getInstance().openProjects.firstOrNull() ?: error("No project found")

        // 模板内容
        val template = """<% block header %>
    <% if title %>
        # <% title %>,
    <% end if %>

<% end block %>

<% block content %>
    <% loop items as item %>
        - <% item.name %>: <% item.value %>
    <% end loop %>
<% end block %>

<% block footer %>
    Generated by Dejavu template engine.
<% end block %>"""

        // 数据
        val data = mapOf(
            "title" to "Hello",
            "items" to listOf(
                mapOf("name" to "Item 1", "value" to "Value 1"),
                mapOf("name" to "Item 2", "value" to "Value 2")
            )
        )

        // 渲染
        val engine = DejavuEngine(project)
        val result = engine.render(template, data)

        // 期望结果
        val expected = """# Hello,

- Item 1: Value 1
- Item 2: Value 2

Generated by Dejavu template engine."""

        assertEquals(expected, result)
    }
}
